### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Fox0205** [gooofy/py-espeak-ng#6]
every time I do esng.say() i get the error a bytes-like object is required, not 'str'.
I haven´t changed anything after i installied it via pip and  just tried your hello World test.
Espeak-NG ist installed and working.

```
>>> esng.say('Hello World!')
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    esng.say('Hello World!')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\espeakng\__init__.py", line 103, in say
    return self._espeak_exe(args, sync=sync)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\espeakng\__init__.py", line 68, in _espeak_exe
    stderr=subprocess.STDOUT)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

**Comment by gooofy** [comment]
looks like you're trying to run this package on a platform that is not supported (this package is GNU/Linux only at this point).
